# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('architools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE_CALL', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='APICall_Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VALUE_NAME', models.CharField(max_length=255)),
                ('VALUE_MEMO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APICallExec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OS_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_LIB', models.CharField(max_length=255)),
                ('API_URL', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tenantlist',
            name='ID_T',
        ),
        migrations.RemoveField(
            model_name='tenantlist',
            name='OS_USERNAME',
        ),
        migrations.AlterField(
            model_name='tenantlist',
            name='OS_PASSWORD',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantlist',
            name='OS_PROJECT_NAME',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantlist',
            name='OS_REGION_NAME',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantlist',
            name='OS_TENANT_ID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenantlist',
            name='OS_TENANT_NAME',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='apicallexec',
            name='ID_API',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.OS_API'),
        ),
        migrations.AddField(
            model_name='apicallexec',
            name='ID_Call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.APICall'),
        ),
        migrations.AddField(
            model_name='apicall_memo',
            name='ID_API',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.OS_API'),
        ),
        migrations.AddField(
            model_name='apicall_memo',
            name='ID_Call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.APICall'),
        ),
        migrations.AddField(
            model_name='apicall',
            name='ID_T',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.TenantList'),
        ),
    ]
