# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architools', '0002_auto_20160323_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantlist',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.AlterField(
            model_name='apicall',
            name='ID_T',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.TENANTLIST'),
        ),
        migrations.AlterField(
            model_name='apicall_memo',
            name='ID_Call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.APICALL'),
        ),
        migrations.AlterField(
            model_name='apicallexec',
            name='ID_Call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.APICALL'),
        ),
    ]
