# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architools', '0006_auto_20160325_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='ID_T',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.TENANTLIST'),
        ),
        migrations.AlterField(
            model_name='apicall_memo',
            name='ID_Call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.APICALL'),
        ),
        migrations.AlterField(
            model_name='apicallexec',
            name='ID_Call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architools.APICALL'),
        ),
    ]
